version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: bus_schedule
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./db/bus_schedule.sql:/docker-entrypoint-initdb.d/bus_schedule.sql
    ports:
      - "5432:5432"

  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - db